version: "3.8"
services:
  # Apache Web Server
  webserver:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html  # Bind mount for the web server
    networks:
      - webnet

  # MySQL Database
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: project
      MYSQL_USER: admin
      MYSQL_PASSWORD: passw0rd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: passw0rd
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
